# Generated by Django 2.0.3 on 2018-03-21 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30, unique=True)),
                ('sobrenome', models.CharField(max_length=30)),
                ('endereço', models.CharField(max_length=250)),
                ('cpf', models.CharField(max_length=11)),
                ('email', models.EmailField(max_length=40)),
                ('telefone', models.CharField(max_length=15)),
            ],
        ),
    ]
